= golang-bittrex-api
Alessandro Sanino <saninoale@gmail.com>

This repository is a golang porting of v2.0 Bittrex API.

Response Type is application/json in case of status code 200 (OK) while it is text/html in case of error 404 (checked 07/24/2017)

== List of endpoints
=== Public API
==== Ping :
URL : https://socket.bittrex.com/signalr/ping

METHOD : `GET`

PARAMS : `_:int`

EXAMPLE : `GET https://socket.bittrex.com/signalr/ping?_=1500913483677`

RESPONSE : 
[source, javascript]
----
{
   Response: "pong"
}
----

COMMENT : Probably `_` is a timestamp.

==== APIVersion :
URL : `https://bittrex.com/Content/version.txt`

METHOD : `GET`

PARAMS : `_:int`

EXAMPLE : `GET https://bittrex.com/Content/version.txt?_=1500912655800`

COMMENT : Probably `_` is a timestamp.

RESPONSE : 
[source, javascript]
----
{
    version : 2.11 // API version
}
----

==== GetBTCPrice :

URL : `https://bittrex.com/Api/v2.0/pub/currencies/GetBTCPrice`

METHOD : `GET`

PARAMS : None

EXAMPLE : `GET https://bittrex.com/Api/v2.0/pub/currencies/GetBTCPrice`

RESPONSE :
[source, javascript]
----
{
    success : true,
    message : "",
    result : {
        bpi : { // ???
            USD : { // USD data 
               code: "USD",
               description: "United States Dollar",
               rate: "2,782.6863",
               rate_float: 2782.6863
            },
            disclaimer: "This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org"
        },
        time : { //time data of operation on coin
            updated: "Jul 24, 2017 16:33:00 UTC",
            updatedISO: "2017-07-24T16:33:00+00:00",
            updateduk: "Jul 24, 2017 at 17:33 BST"
        }
    }
}
----


==== GetMarketSummaries :

URL : `https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries`

METHOD : `GET`

PARAMS : `_:int`

EXAMPLE : `GET https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries?_=1500913483670`

COMMENT : Probably `_` is a timestamp.

RESPONSE :
[source, javascript]
----
{ 
    message : '',
    success : true,
    result : [ //array
    {
        IsVerified : false,
        Market : { // Market object
            BaseCurrency : "BITCNY",
            BaseCurrencyLong : "BitCNY",
            Created : "2015-12-11T06:31:40.653",
            IsActive : true,
            IsSponsored : null,
            LogoUrl : null,
            MarketCurrency : "BTC",
            MarketCurrencyLong : "Bitcoin",
            MarketName : "BITCNY-BTC",
            MinTradeSize : 1e-8,
            Notice : ""
        },
        Summary : { //MarketSummary object
            Ask: 18619.09547372,
            BaseVolume: 16801.39641099,
            Bid: 18101.72000003,
            Created: "2015-12-11T06:31:40.653",
            High: 18989.52,
            Last: 18359.80273687,
            Low: 17600.14,
            MarketName: "BITCNY-BTC",
            OpenBuyOrders: 440,
            OpenSellOrders: 237,
            PrevDay: 18100,
            TimeStamp: "2017-07-24T16:24:28.54",
            Volume: 0.91026451
        }
    },
    ...
    { ... }
    ]
}
----

==== GetCurrencyInfo :

URL : `https://bittrex.com/api/v2.0/pub/Currency/GetCurrencyInfo`

METHOD : `POST`

PARAMS : `currencyName:string`, `__RequestVerificationToken:string`

EXAMPLE : POST `https://bittrex.com/api/v2.0/pub/Currency/GetCurrencyInfo` with data : `{ currencyName: "CVC", __RequestVerificationToken: "HIDDEN_FOR_PRIVACY"}`

RESPONSE : 
[source, javascript]
----
{
    success : true,
    message : "",
    result : {
        BaseAddress:"0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98",
        CoinType: "ETH_CONTRACT",
        Currency: "CVC",
        CurrencyLong: "Civic"
        Health : { // CoinHealth object
            BlockHeight: 4067747,
            Currency: "CVC",
            DepositQueueDepth: 0,
            IsActive: true,
            LastChecked: "2017-07-24T16:53:00.33",
            MinutesSinceBHUpdated: 0,
            WalletBalance: 0,
            WalletConnections: 0,
            WithdrawQueueDepth: 0
        },
        IsActive: true,
        MinConfirmation: 36,
        Notice: null,
        TxFee: 0.01
    }
}
----

COMMENT : Probably this request requires authentication.

==== GetTicks

URL : `https://bittrex.com/Api/v2.0/pub/market/GetTicks`

METHOD : `GET`

PARAMS : `marketName:string`, `tickInterval:string`, `_:int`

EXAMPLE : `https://bittrex.com/Api/v2.0/pub/market/GetTicks?marketName=BTC-CVC&tickInterval=thirtyMin&_=1500915289433`

RESPONSE :
[source, javascript]
----
{
    success : true,
    message : "",
    result : [ // Array of candles
    {
        BV: 13.14752793,          // ?????
        C: 0.000121,              // close
        H: 0.00182154,            // high
        L: 0.0001009,             // low
        O: 0.00182154,            // open
        T: "2017-07-16T23:00:00", // timestamp
        V: 68949.3719684          // 24h volume ??
    },
    ...
    { ... }
    ]
    
}
----
